name: Build and Push Docker image to ECR

on:
  push:
    branches: [main]  # Adjust if your default branch is named differently

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        IMAGE_URI=173898094405.dkr.ecr.ap-southeast-2.amazonaws.com/rodmanr90/githubactions
        docker build -t $IMAGE_URI .

    - name: Push Docker image
      run: |
        IMAGE_URI=173898094405.dkr.ecr.ap-southeast-2.amazonaws.com/rodmanr90/githubactions
        docker push $IMAGE_URI